export const VERSION = 'VERSION'
export const PORT = 'PORT'
export const ENVIRONMENT = 'ENVIRONMENT'
export const TYPEORM = {
	HOST: 'TYPEORM_HOST',
	PORT: 'TYPEORM_PORT',
	DATABASE: 'TYPEORM_DATABASE',
	USERNAME: 'TYPEORM_USERNAME',
	PASSWORD: 'TYPEORM_PASSWORD',
}
export const REDIS = {
	HOST: 'REDIS_HOST',
	PORT: 'REDIS_PORT',
	USER: 'REDIS_USER',
	PASSWORD: 'REDIS_PASSWORD',
}
export const SENTRY = {
	DSN: 'SENTRY_DSN',
}
