export const VERSION = 'VERSION'
export const PORT = 'PORT'
export const ENVIRONMENT = 'ENVIRONMENT'
export const TYPEORM = {
	HOST: 'TYPEORM.HOST',
	PORT: 'TYPEORM.PORT',
	DATABASE: 'TYPEORM.DATABASE',
	USERNAME: 'TYPEORM.USERNAME',
	PASSWORD: 'TYPEORM.PASSWORD',
}
export const SENTRY = {
	DSN: 'SENTRY.DSN',
}
