export const ENVIRONMENT = {
	TEST: 'TEST',
	LOCAL: 'LOCAL',
	DEVELOPMENT: 'DEVELOPMENT',
	STATGING: 'STATGING',
	PRODUCTION: 'PRODUCTION',
}

export enum REPORT_STATUS {
	REPORTED = 'REPORTED',
	APPLIED = 'APPLIED',
	DENIED = 'DENIED',
}

const constants = {
	ENVIRONMENT,
}

export default constants
