name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build migrations
      - name: Cache migrations
        id: migration-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-migrations
        with:
          path: server
          key: ${{ runner.os }}-${{env.cache-name}}-${{ hashFiles('**/typeorm/**/*.ts') }}
            ${{ runner.os }}-${{env.cache-name}}-
      - name: Build
        if: steps.migration-cache.outputs.cache-hit != 'true'
        run: yarn run build

      # Test
      - name: Test
        run: |
          yarn run test:cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Test(e2e)
        run: |
          yarn run test:e2e
