name: Sentry

on:
  push:
    tags:
       - '*'

jobs:
  upload-source-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{env.cache-name}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{env.cache-name}}-
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      # Build files
      - name: Build
        run: npm run build

      # Create .sentryclirc
      - name: Create .sentryclirc
        env:
          SENTRY_CLI_RC: ${{ secrets.SENTRY_CLI_RC }}
        run: |
          echo "$SENTRY_CLI_RC" > .sentryclirc

      # Upload Source Map
      - name: Upload Source Map
        run: |
          npm run sentry:releases -- files ${GITHUB_REF##*/} upload-sourcemaps ./server/src
